### ISSUE TITLE
Allow to use different term emulator

### ISSUE THREAD

**Issue by radmen** [xvw/qian#2]
### Problem

Right now opening directory in terminal opens native osx terminal emulator. It would be nice to choose in which terminal should be directory opened (in my case: iterm2)

**Comment by xvw** [comment]
Yes, I use iTerm2 too. 
This issue is related to a more "huge" plan to allow "custom configuration". But I agree with your point

**Comment by radmen** [comment]
Aye. I saw that there's no config section :)

Thanks!

**Comment by xvw** [comment]
It is Work in progress on the branch develop

**Comment by radmen** [comment]
Are you talking about this line? https://github.com/xvw/qian/blob/develop/static/js/index.js#L16 :)

**Comment by xvw** [comment]
Actually, Yes, but When i have finished the "global code restructuration", you will able to update the configuration into the GUI. 
My actual roadmap is : 
- Finish the "search engine" (using fuzz-search, like you)
- write a GUI to change the default terminal app
- improve the keybindings 

When it will be done, I will merge in master (and package the app for a first release)

**Comment by radmen** [comment]
Yay! I'll wait for it :)
